inc:
  # Blog Information
  title:        "dgblog"
  subtitle:     'Porque tenemos un "huevo" de ideas por compartir =)'
  cover_image:  cover.jpg
  logo:         logo.png
  
  # Company information
  company:      dgnest
  url:          http://dgnest.com/
  facebook:     dgnest
  twitter:      dgnest
  gplus:        '112145396131431749370'
  about_link:   /post/2014/08/07/dgnest/
  
  # Product Information
  product_link: http://dgnest.com/
  tagline:      "Conviértete en un verdadero maker ..."
  
  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  dgnest
  
  # Sharing settings
  sharing:
    twitter:    dgnest
    facebook:   dgnest
    gplus:      dgnest
    hn:         false
    
  # Analytics     
  analytics:
    google: true # Add tracking code in _includes/_google-analytics.html
      
  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Droid+Serif:400,700'
  
  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

url:         http://blog.dgnest.com
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
timezone:    America/Lima

# Show future posts
future:      true
limit_posts: 0
highlighter: pygments

relative_permalinks: true

permalink: pretty
paginate_path: 'page:num'
paginate: 5

markdown:      kramdown
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "<!-- more -->"

lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true

# minify html
env: production

gems:
  - jekyll-sitemap

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: hard
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false